### ISSUE TITLE
Persistent Input Method Indicator Issue on Parrot OS (Staying up above all windows)

### ISSUE THREAD

**Issue by MossesRoss** [ParrotSec/parrot-menu#16]
After clicking on the input method indicator in the panel (English - English (US)), the indicator persists and does not go away, even after trying to close it. This issue appears in the Parrot OS interface (IBus Preferences - I guess
![Issue - it's still here](https://github.com/user-attachments/assets/6d5d2d51-b65c-494d-8dcf-4121c7815edf)
![Issue Screen Shot 2](https://github.com/user-attachments/assets/c1da9e61-c1dc-4b4c-8d30-857a7f4872f1)
![Issue Screen Shot 1](https://github.com/user-attachments/assets/17a5999b-c8e8-418e-8e4e-640924cd0eda)
![Issue Screen Shot](https://github.com/user-attachments/assets/cb9244c9-423a-4a71-abcf-07ae61abaa63)
). Screenshot attached for reference.

**Comment by PalinuroSec** [comment]
thanks for reporting that.

unfortunately the affected component is not handled by parrot.

parrot uses the debian provided mate version, which is 1.26 and has been 1.26 since at least 3 years, and this version has several bugs and memory holes.

some of them were addressed in the latest 1.28 version, but nobody cared to package it for debian.

the worst thing is that the debian project will soon enter its first freezing stages for debian 13 trixie, and if nobody ports the new mate desktop in time, we will have the old 1.26 from october 2021 for another 2 years, which is awful

**Comment by MossesRoss** [comment]
Thanks bro, So this should be closed now, eh? (I partially understood what you're trying to say, but thank you so much for fast replay)
